# étape de build
FROM node:lts-alpine as build-stage
#ATTENTION!!!!!! INSTALLER GIT! car il y a certaine dependances sur git (Résolution not found /app/node_modules)
RUN apk add git
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build

# étape de production
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]